"""Script to generate products_v1.csv and products_v1_log.md with strict validation against API contract."""

import csv
from pathlib import Path

# Contract allowed values
ALLOWED_RELATIONSHIPS = {
    "mother", "father", "friend", "best_friend", "partner", "brother", "sister", "teacher", "colleague", "other"
}
ALLOWED_AGE_GROUPS = {
    "5_9", "10_19", "20_24", "25_29", "30_39", "40_49", "50_plus"
}
ALLOWED_GENDERS = {"male", "female", "unspecified", ""}
ALLOWED_OCCASIONS = {
    "birthday", "wedding", "anniversary", "graduation", "engagement", "thank_you", "valentines_day", "eid", "christmas", "other"
}
ALLOWED_INTERESTS = {
    "beauty", "skincare", "makeup", "books", "technology", "computer_gadgets", "mobile_accessories", "sports", "cricket", "fitness", "fashion", "jewelry", "gaming", "travel", "home_lifestyle", "food", "art_crafts", "other"
}
ALLOWED_STYLES = {
    "practical", "elegant", "luxury", "budget_friendly", "personalized", "sentimental", "fun", "minimal", "self_care", "experience"
}
ALLOWED_AVAILABILITY = {"in_stock", "out_of_stock", "unknown"}

PRODUCTS = [
    # 1. skincare_gift_set
    {
        "name": "Pond's Pure Bright Facial Foam 100g & Bright Beauty 50g Combo",
        "description": "A daily cleansing and brightening facial wash duo formulated with activated charcoal and vitamin B3. Suitable for refreshing everyday skincare routines.",
        "price": 635,
        "category_id": "skincare_gift_set",
        "tags": "facewash|charcoal|cleanser|skincare|combo",
        "interests": "skincare|beauty",
        "occasions": "birthday|thank_you|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "practical|budget_friendly|self_care",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/4f17734125b271d49db4c885da1952e4.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/ponds-pure-bright-facial-foam-100g-free-bright-beauty-50g-i503251717.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:08:20+05:00",
    },
    {
        "name": "Vince Organix Glow & Radiance Skincare Kit",
        "description": "An organic face care bundle designed to enhance skin clarity and hydration. Features nourishing botanical extracts for a gentle radiant complexion.",
        "price": 2830,
        "category_id": "skincare_gift_set",
        "tags": "serum|radiance|glow|vince|moisturizer",
        "interests": "skincare|beauty",
        "occasions": "birthday|eid|wedding|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "female",
        "styles": "self_care|elegant|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/56143c7b74f3fcb6528d9c15d4d3d191.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/vince-organix-glow-radiance-kit-i422176466.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:08:44+05:00",
    },
    {
        "name": "Conatural Intense Luster Hair & Skincare Combo Pack of 2",
        "description": "A revitalizing organic duo crafted to deeply condition hair roots and restore natural skin moisture. Made with pure oils and botanical extracts.",
        "price": 4008,
        "category_id": "skincare_gift_set",
        "tags": "conatural|organic|haircare|skincare|combo",
        "interests": "skincare|beauty",
        "occasions": "birthday|anniversary|wedding|eid",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "female",
        "styles": "self_care|luxury|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/3b12dc86c54784408d6d2a588b56d353.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/conatural-intense-luster-hair-combo-pack-of-2-i545620023.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:10+05:00",
    },
    {
        "name": "The Ordinary Anti Aging & Brightening Complete Skincare Set",
        "description": "A high-performance serum regimen including Multi-Peptide Buffet, Niacinamide, and Caffeine Solution. Targets fine lines, uneven texture, and under-eye fatigue.",
        "price": 9499,
        "category_id": "skincare_gift_set",
        "tags": "theordinary|serum|antiaging|niacinamide|peptides",
        "interests": "skincare|beauty",
        "occasions": "birthday|wedding|anniversary",
        "age_groups": "25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|self_care|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/7bcf914ee712c9c748c9735d4ad1e847.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/the-ordinary-anti-aging-set-multi-peptide-serum-buffet-niacinamide-10-zinc-1-caffeine-solution-5-egcg-bundle-set-i438784792.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:35+05:00",
    },

    # 2. beauty_gift_set
    {
        "name": "Professional All-In-One Bridal Makeup Gift Kit",
        "description": "A compact cosmetic kit containing eyeshadows, blushers, and lip colors for beginner and festive makeup. An accessible gift for girls and young adults.",
        "price": 899,
        "category_id": "beauty_gift_set",
        "tags": "makeup|cosmetics|eyeshadow|blush|giftkit",
        "interests": "makeup|beauty|fashion",
        "occasions": "birthday|eid|thank_you",
        "age_groups": "10_19|20_24|25_29",
        "genders": "female",
        "styles": "budget_friendly|fun|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/0be91db405626027c44243a7a9775f5c.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/best-gift-makeup-kit-for-professionals-and-bridals-best-quality-makeup-kit-bridal-makeup-kit-professional-makeup-kit-all-in-one-professional-cosmetic-women-best-makeup-kit-for-girls-and-women-i445805939.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:11:15+05:00",
    },
    {
        "name": "13 in 1 Complete Makeup Gift Set for Girls & Women",
        "description": "A comprehensive beauty package with foundation, primer, eyeshadow palette, mascara, and makeup fixer. Covers the essential steps for full party makeup.",
        "price": 2399,
        "category_id": "beauty_gift_set",
        "tags": "makeupkit|foundation|mascara|palette|lipstick",
        "interests": "makeup|beauty|fashion",
        "occasions": "birthday|wedding|eid|engagement",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "female",
        "styles": "practical|fun|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/65caad6fb7e2467d3e6d8a4362aa6cbe.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/13-in-1-makeup-kit-for-girls-women-complete-makeup-set-with-foundation-primer-concealer-eyeshadow-palette-compact-powder-lipstick-mascara-makeup-fixer-i1948122554.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:11:40+05:00",
    },
    {
        "name": "Full Professional 190 Color Palette Makeup Vanity Set",
        "description": "An extensive makeup artist palette featuring 190 pigmented shades of eyeshadow, contour, and highlight powders. Ideal for creative and festive styling.",
        "price": 6799,
        "category_id": "beauty_gift_set",
        "tags": "eyeshadowpalette|190color|vanity|professional|makeup",
        "interests": "makeup|beauty|art_crafts",
        "occasions": "wedding|anniversary|birthday|engagement",
        "age_groups": "20_24|25_29|30_39",
        "genders": "female",
        "styles": "luxury|elegant|fun",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/823ad759bca4023dddfb45cc0be4e870.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/190-i432422896.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:11:55+05:00",
    },
    {
        "name": "Miss Rose 140 Color All-In-One Vanity Case Makeup Kit",
        "description": "A luxury multi-tier travel makeup trunk equipped with eyeshadows, face powders, highlighters, and brushes. An impressive celebratory gift.",
        "price": 10000,
        "category_id": "beauty_gift_set",
        "tags": "missrose|vanitycase|allinone|bridalmakeup|luxury",
        "interests": "makeup|beauty|fashion",
        "occasions": "wedding|engagement|anniversary|birthday",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "female",
        "styles": "luxury|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/dc1d46b7a2d480be40a6b60ad2e24021.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/140-i1950572516.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:12:08+05:00",
    },

    # 3. self_care_hamper
    {
        "name": "Daily Skincare Gift Pack Face Wash Day Cream & Serum Kit",
        "description": "A hydrating self-care trio containing gentle cleanser, moisturizing cream, and nourishing face serum. Provides an uplifting daily skincare routine.",
        "price": 799,
        "category_id": "self_care_hamper",
        "tags": "selfcare|cream|serum|facewash|giftpack",
        "interests": "skincare|beauty|home_lifestyle",
        "occasions": "birthday|thank_you|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "self_care|budget_friendly|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/78be05c56b6c003fc1c4cae4eebeecfc.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i944649678.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:12:26+05:00",
    },
    {
        "name": "Scents N Secrets Romanian Blue Bath & Body Gift Box",
        "description": "An aromatic luxury bathing assortment with body wash, fragranced lotion, and mist in calming notes. Perfect for soothing home pampering sessions.",
        "price": 3411,
        "category_id": "self_care_hamper",
        "tags": "bathandbody|scents|fragrance|lotion|showergel",
        "interests": "beauty|home_lifestyle",
        "occasions": "birthday|anniversary|eid|thank_you",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "self_care|elegant|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/3e6fe684be76fc3fa23b5d2ba06466f8.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i596059362.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:12:35+05:00",
    },
    {
        "name": "Scents N Secrets I Love Oud Bath & Body Luxury Gift Box",
        "description": "A rich oriental fragrance gift box containing body wash, nourishing lotion, and long-lasting oud scent mist. Ideal for relaxing evening aromatherapy.",
        "price": 3667,
        "category_id": "self_care_hamper",
        "tags": "oud|bathandbody|fragrance|pampering|luxurybox",
        "interests": "beauty|home_lifestyle",
        "occasions": "wedding|anniversary|eid|birthday",
        "age_groups": "25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|self_care|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/74ebff224959db62c974c83fc67fa091.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/i-love-i596096063.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:12:43+05:00",
    },
    {
        "name": "Remington PG180 Pilot Grooming Self-Care Kit",
        "description": "A precision personal grooming kit featuring washable steel trimmer blades, beard combs, and detail cutters. Delivers dependable grooming convenience.",
        "price": 9000,
        "category_id": "self_care_hamper",
        "tags": "remington|grooming|trimmer|personalcare|shaver",
        "interests": "beauty|technology",
        "occasions": "birthday|graduation|eid|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "male",
        "styles": "practical|self_care|luxury",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/92ffbcfbc6a117b96057a7ebc40e6988.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/pg180-i2672199.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:12:59+05:00",
    },

    # 4. tech_gadgets
    {
        "name": "Portable Tech Travel Cable Organizer Waterproof Storage Case",
        "description": "A durable multi-compartment travel organizer designed to protect power banks, USB cords, flash drives, and adapters. Keeps digital essentials neatly sorted.",
        "price": 729,
        "category_id": "tech_gadgets",
        "tags": "cableorganizer|techpouch|travelcase|accessories",
        "interests": "technology|travel|computer_gadgets",
        "occasions": "graduation|birthday|thank_you",
        "age_groups": "10_19|20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "practical|minimal|budget_friendly",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/73ca9fc76d75dbeee84d8583fb22eb82.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/travel-cable-organizer-waterproof-electronic-accessories-storage-pouch-portable-tech-accessories-carry-case-waterproof-cable-gadget-organizer-bag-electronic-travel-storage-bag-multi-purpose-cable-organizer-gadget-pouch-i1947776530.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:08:15+05:00",
    },
    {
        "name": "3-in-1 Fast Wireless Charging Station Dock for Phone & Earbuds",
        "description": "A streamlined desktop wireless charging station that powers compatible smartphones, smartwatches, and earbuds simultaneously with over-current safety.",
        "price": 2499,
        "category_id": "tech_gadgets",
        "tags": "wirelesscharger|fastcharging|dock|desktop|3in1",
        "interests": "technology|mobile_accessories|computer_gadgets",
        "occasions": "birthday|graduation|eid|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "practical|minimal|fun",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/be9012a64c48972e3914e666a0d0a51c.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/3-i489397923.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:08:45+05:00",
    },
    {
        "name": "A4Tech HS-50 ComfortFit Stereo Headset with Noise Cancelling Mic",
        "description": "An ergonomic over-ear stereo headset equipped with plush ear cushions and noise-filtering microphone. Delivers clear acoustics for calls and music.",
        "price": 4099,
        "category_id": "tech_gadgets",
        "tags": "a4tech|headset|headphones|microphone|audio",
        "interests": "technology|computer_gadgets|gaming",
        "occasions": "birthday|graduation|thank_you",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "practical|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/5a2d6e386ce056dbe1267428f5c90ec9.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/a4-hs-50-i592439570.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:12+05:00",
    },
    {
        "name": "120W Fast Charging 10000mAh Power Bank Digital Display",
        "description": "A high-capacity portable power bank equipped with 120W rapid charging capability and intelligent LED status readout. Powers multiple mobile devices safely on the go.",
        "price": 10000,
        "category_id": "tech_gadgets",
        "tags": "powerbank|fastcharge|10000mah|digitaldisplay|portable",
        "interests": "technology|mobile_accessories|travel",
        "occasions": "birthday|graduation|anniversary|eid",
        "age_groups": "20_24|25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|practical|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/d96853fc245f7c3ddf8c9b2079a4ae4f.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/120w-10000-3-i935231564.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:40+05:00",
    },

    # 5. mobile_accessories_bundle
    {
        "name": "Xiaomi 67W Turbo Charger Adapter with 1m Fast Cable Bundle",
        "description": "An authentic high-speed wall charging set engineered with smart heat dissipation and quick power output. Compatible with modern Type-C smartphones.",
        "price": 1377,
        "category_id": "mobile_accessories_bundle",
        "tags": "xiaomi|fastcharger|67w|typec|turbocharge",
        "interests": "mobile_accessories|technology",
        "occasions": "birthday|thank_you|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "practical|budget_friendly|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/2bcba2d8bf45eef7253a992e4aa1a5f6.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/xiaomi-67w-turbo-charger-bundle-with-1m-usb-cable-decimal-charger-for-redmik30pocoxiaomi-devices-i573811914.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:08:35+05:00",
    },
    {
        "name": "3-in-1 Mobile Gaming Accessories Bundle for PUBG Mobile",
        "description": "A tactile mobile gaming combo containing responsive triggers, precision capacitive stylus, and non-slip thumb sleeves. Enhances control during competitive matches.",
        "price": 2897,
        "category_id": "mobile_accessories_bundle",
        "tags": "pubg|mobilegaming|triggers|fingersleeves|accessories",
        "interests": "gaming|mobile_accessories|technology",
        "occasions": "birthday|eid|graduation",
        "age_groups": "10_19|20_24|25_29",
        "genders": "",
        "styles": "fun|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/7cb185c7e09e25d259e863ea6be43e0e.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/high-quality-gaming-keyboard-and-mouse-combo-with-rgb-side-led-panel-mechanical-feeling-wired-keyboard-2400-dpi-mouse-with-free-mouse-pad-for-pubg-mobile-laptop-pc-computer-3-in-1-gaming-bundle-black-white-green-i1947084835.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:08:55+05:00",
    },
    {
        "name": "AWA 12-in-1 Smartphone Universal Accessory Mega Bundle",
        "description": "An all-inclusive mobile utility bundle featuring phone stand, car mount, OTG adapters, selfie ring light, and braided charging cords.",
        "price": 4200,
        "category_id": "mobile_accessories_bundle",
        "tags": "megabundle|phonestand|otg|cables|accessories",
        "interests": "mobile_accessories|technology|computer_gadgets",
        "occasions": "birthday|graduation|anniversary|thank_you",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "practical|budget_friendly",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/f228b3769c3a2153573e87854eb130f4.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/awa-12-awa-1-12-awa-12-awa-i885285263.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:20+05:00",
    },
    {
        "name": "WiWU 4-in-1 Tech Travel Organizer Combo Kit 10000mAh",
        "description": "A premium traveler's mobile power pack featuring a magnetic 10000mAh battery pack, universal adapter plugs, braided cables, and shockproof hardshell case.",
        "price": 9190,
        "category_id": "mobile_accessories_bundle",
        "tags": "wiwu|magneticpowerbank|travelset|premium|combo",
        "interests": "mobile_accessories|technology|travel",
        "occasions": "graduation|birthday|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|practical|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/4eb4ba52f75961e967a57fa87309de9b.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/wiwu-4-in-1-10000mah-i1965780748.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:50+05:00",
    },

    # 6. book_bundle
    {
        "name": "Pack of 6 Self Help & Motivation Bestseller Books Bundle",
        "description": "An inspiring book package containing Ikigai, The Power of Discipline, Attitude is Everything, and other personal growth bestsellers. A thoughtful gift for curious minds.",
        "price": 799,
        "category_id": "book_bundle",
        "tags": "books|selfhelp|motivation|ikigai|discipline",
        "interests": "books",
        "occasions": "birthday|graduation|thank_you|eid",
        "age_groups": "10_19|20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "sentimental|practical|budget_friendly",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/4f7fc2431cf8ca35086b59ca9e33465d.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/pack-of-6-pcs-self-help-motivation-books-bundle-the-power-of-discipline-ikigai-the-art-of-being-alone-the-art-of-laziness-attitude-is-everything-the-48-laws-of-power-best-english-novel-_ks-i1950740132.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:05+05:00",
    },
    {
        "name": "Dandadan Volumes 1-5 Ultimate Manga Collection Set",
        "description": "The first five action-packed volumes of the popular sci-fi supernatural manga series in English print. Packed with thrilling humor and dynamic storytelling.",
        "price": 2999,
        "category_id": "book_bundle",
        "tags": "manga|dandadan|anime|comic|bookset",
        "interests": "books|art_crafts|gaming",
        "occasions": "birthday|eid|graduation",
        "age_groups": "10_19|20_24|25_29",
        "genders": "",
        "styles": "fun|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/6e088a8296eb4c718a5949d2685dd2a1.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/dandadan-volumes-1-5-ultimate-book-collection-manga-set-by-yukinobu-tatsu-ultimate-manga-bundle-english-language-edition-collectors-pack-_am-i1962391392.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:25+05:00",
    },
    {
        "name": "A Court of Thorns and Roses 5 Book Series Bundle Sarah J Maas",
        "description": "The complete five-book fantasy romance saga following Feyre's magical adventures across fairy lands. Bound in matching paperback editions.",
        "price": 5345,
        "category_id": "book_bundle",
        "tags": "acotar|fantasy|fiction|sarahjmaas|novels",
        "interests": "books",
        "occasions": "birthday|anniversary|eid",
        "age_groups": "20_24|25_29|30_39",
        "genders": "",
        "styles": "sentimental|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/94aa82c16260a92f80c65cbe10996614.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/a-court-of-thorns-and-roses-5-book-bundle-sarah-j-maas-i876627886.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:09:45+05:00",
    },
    {
        "name": "The Wardstone Chronicles Spook's Complete 13 Book Set",
        "description": "The entire 13-book dark fantasy collector's edition detailing the Spook apprentice's adventures against ancient witches and spirits. A grand gift for book lovers.",
        "price": 7145,
        "category_id": "book_bundle",
        "tags": "spooks|wardstone|chronicles|darkfantasy|boxset",
        "interests": "books",
        "occasions": "birthday|graduation|anniversary",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "luxury|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/6abf6fa595bc09e99a84a60e06ae2d7e.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/the-spooks-apprentice-the-spooks-curse-the-spooks-secret-the-spooks-battle-the-spooks-mistake-the-spooks-sacrifice-the-spooks-nightmare-the-spooks-destiny-spooks-i-am-grimalkin-blood-slithers-tale-alice-revenge-i494871486.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:10:05+05:00",
    },

    # 7. fitness_gear
    {
        "name": "11-Piece Power Resistance Bands Workout Training Set",
        "description": "A versatile home fitness band kit including 5 resistance tubes, cushioned handles, ankle straps, and door anchor. Supports full body calisthenics.",
        "price": 1098,
        "category_id": "fitness_gear",
        "tags": "resistancebands|workout|fitness|gym|exercise",
        "interests": "fitness|sports",
        "occasions": "birthday|graduation|thank_you",
        "age_groups": "10_19|20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "practical|budget_friendly|self_care",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/617da5b72e7d79b2075775c7423984d7.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/11-5-i261124458.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:13:22+05:00",
    },
    {
        "name": "Anti-Slip 10mm Extra Thick Yoga & Exercise Mat 72x24 Inch",
        "description": "A high-density cushioning workout mat with textured non-slip surface and carrying strap. Ideal for floor pilates, stretching, and yoga poses.",
        "price": 1899,
        "category_id": "fitness_gear",
        "tags": "yogamat|pilates|floormat|exercise|cushioning",
        "interests": "fitness|sports",
        "occasions": "birthday|anniversary|eid",
        "age_groups": "20_24|25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "self_care|practical|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/5a646c2685714399e52cefe9aa8784d5.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/10-72-24-i433184684.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:14:57+05:00",
    },
    {
        "name": "Adjustable Multi-Position Weight Bench Press",
        "description": "A heavy-duty steel exercise bench with multi-angle backrest adjustments for flat and incline dumbbell training. Enhances home strength workouts.",
        "price": 4799,
        "category_id": "fitness_gear",
        "tags": "weightbench|benchpress|gymequipment|dumbbellbench|strength",
        "interests": "fitness|sports",
        "occasions": "birthday|graduation|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "practical|luxury",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/45564883f3bf74ea1e5d7966ef47e62d.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i399884149.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:15:28+05:00",
    },
    {
        "name": "Heavy-Duty Incline Decline Straight Workout Bench Press",
        "description": "A reinforced commercial-style gym bench designed for full body barbell and dumbbell routines. Built with padded leatherette seating and rubber footpads.",
        "price": 8799,
        "category_id": "fitness_gear",
        "tags": "inclinebench|workoutbench|gymgear|weightlifting|fitness",
        "interests": "fitness|sports",
        "occasions": "birthday|anniversary|graduation",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "practical|luxury",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/48430ea450ee63c95a201b2390234127.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i209496287.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:16:00+05:00",
    },

    # 8. jewelry_set
    {
        "name": "Artificial Bridal Fashion Jewelry Set with Matching Earrings",
        "description": "A delicate traditional jewelry set featuring an ornate choker necklace, matching drop earrings, and maang tikka with crystal accents.",
        "price": 662,
        "category_id": "jewelry_set",
        "tags": "jewelry|necklace|earrings|tikka|artificialjewelry",
        "interests": "jewelry|fashion",
        "occasions": "wedding|eid|birthday",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "female",
        "styles": "budget_friendly|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/57e79391d45ee0c96c56784d939fc9b4.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/00765403-i410655537.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:16:38+05:00",
    },
    {
        "name": "Zircon Micro-Setting Bridal Pendant & Earrings Jewelry Set",
        "description": "A sparkling rhodium-plated jewelry ensemble encrusted with cubic zirconia stones. Adds sophisticated shine to festive and evening attire.",
        "price": 1599,
        "category_id": "jewelry_set",
        "tags": "zircon|bridalset|rhodium|pendant|earrings",
        "interests": "jewelry|fashion",
        "occasions": "wedding|engagement|anniversary|birthday",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "female",
        "styles": "elegant|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/4657ea5976ea6e73708e9ca3a47318ec.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i433857572.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:17:08+05:00",
    },
    {
        "name": "Kundan & Pearl Heritage Bridal Jewelry Set",
        "description": "An exquisite artisanal bridal set adorned with handcrafted kundan stones and clustered faux seed pearls. Perfectly complements traditional wedding wear.",
        "price": 3550,
        "category_id": "jewelry_set",
        "tags": "kundan|pearls|bridalset|traditional|necklace",
        "interests": "jewelry|fashion",
        "occasions": "wedding|engagement|eid|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "female",
        "styles": "luxury|elegant|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/432095f6dc15560b73c4d9cb9c025095.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i430750880.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:17:39+05:00",
    },
    {
        "name": "Premium Gold-Plated Long-Lasting Bridal Jewelry Set",
        "description": "A regal high-polish bridal jewelry set embellished with gemstone inlays and intricate filigree work. Presented in a luxury gift case.",
        "price": 9999,
        "category_id": "jewelry_set",
        "tags": "goldplated|bridalset|filigree|regal|luxuryjewelry",
        "interests": "jewelry|fashion",
        "occasions": "wedding|engagement|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49|50_plus",
        "genders": "female",
        "styles": "luxury|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/f2390f7a0dc1ea857d47669466547144.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i629009373.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:18:01+05:00",
    },

    # 9. cricket_gear
    {
        "name": "Saki Sports Cricket Bat 2026 Full Size Tape Ball Bat",
        "description": "A lightweight wooden tape-ball cricket bat shaped with thick power edges and a balanced pickup. Engineered for street and tournament play.",
        "price": 1049,
        "category_id": "cricket_gear",
        "tags": "cricketbat|tapeball|sakisports|poweredges|cricket",
        "interests": "cricket|sports",
        "occasions": "birthday|eid|graduation",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "male",
        "styles": "practical|fun|budget_friendly",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/5a91ca5f6c88dd9652a92e105e4c6981.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/2026-i936886422.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:20:30+05:00",
    },
    {
        "name": "Personal Cricket Kit Bag Duffle Bag Large Size with Bat Pocket",
        "description": "A spacious water-resistant cricket duffle bag featuring reinforced shoulder straps and dedicated bat compartments. Fits full personal equipment comfortably.",
        "price": 1559,
        "category_id": "cricket_gear",
        "tags": "kitbag|cricketbag|dufflebag|sportsgear|cricket",
        "interests": "cricket|sports",
        "occasions": "birthday|graduation|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "male",
        "styles": "practical|budget_friendly",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/55ca562725fa8b30d8c07e05fc8676d3.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i435209405.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:20:45+05:00",
    },
    {
        "name": "SS TON Professional Editions Hard Ball Cricket Bat",
        "description": "A handcrafted hard-ball cricket bat fashioned from seasoned willow with responsive rebound sweetspot. Designed for competitive club and turf tournaments.",
        "price": 3987,
        "category_id": "cricket_gear",
        "tags": "sston|hardballbat|cricketbat|clubcricket|cricket",
        "interests": "cricket|sports",
        "occasions": "birthday|graduation|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "male",
        "styles": "practical|fun",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/ff391d46f5eb4d72d242687d6052f5ee.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/ss-ton-2023-editions-hard-ball-cricket-bat-for-professional-players-i1965918221.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:21:36+05:00",
    },
    {
        "name": "Taimoor F Plus Premium English Willow Cricket Bat Full Size",
        "description": "A top-tier English willow cricket bat featuring straight grains, oversized profile, and feather-light pickup balance. Built for high-impact stroke play.",
        "price": 7900,
        "category_id": "cricket_gear",
        "tags": "englishwillow|taimoor|cricketbat|hardball|premiumcricket",
        "interests": "cricket|sports",
        "occasions": "birthday|graduation|anniversary|eid",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "male",
        "styles": "luxury|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/5a2d6771cfd65ceb15cb27863bf18ca1.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/f-i1968644371.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:21:03+05:00",
    },

    # 10. gaming_accessories
    {
        "name": "RGB 7-Color Backlit Precision Wired Gaming Mouse",
        "description": "An ergonomic 7-button optical gaming mouse featuring dynamic breathing RGB backlighting and adjustable DPI tracking. Provides crisp clicks and smooth glide.",
        "price": 1397,
        "category_id": "gaming_accessories",
        "tags": "gamingmouse|rgb|opticalmouse|dpi|gaminggear",
        "interests": "gaming|technology|computer_gadgets",
        "occasions": "birthday|graduation|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "fun|budget_friendly|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/bb430d85ef418728d10b7ee0c1a92358.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/7-i1959941878.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:21:54+05:00",
    },
    {
        "name": "PRO II RGB Stereo Gaming Headphones with Noise Cancelling Mic",
        "description": "An immersive gaming headset fitted with 50mm dynamic drivers, deep bass chamber, and flexible noise-suppression boom mic for voice chat.",
        "price": 2297,
        "category_id": "gaming_accessories",
        "tags": "gamingheadset|headphones|rgb|noisecancelling|mic",
        "interests": "gaming|technology|computer_gadgets",
        "occasions": "birthday|graduation|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "fun|practical",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/16ee1b1ca29d107a61d15442dfa8fa5b.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/71-4-i478130174.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:22:31+05:00",
    },
    {
        "name": "RGB K61 60% Compact Mechanical Gaming Keyboard Blue Switch",
        "description": "A space-saving 61-key mechanical gaming keyboard with clicky blue switches, detachable Type-C cable, and vibrant RGB lighting modes.",
        "price": 3949,
        "category_id": "gaming_accessories",
        "tags": "mechanicalkeyboard|blueswitch|60percent|rgbkeyboard|gaming",
        "interests": "gaming|technology|computer_gadgets",
        "occasions": "birthday|graduation|eid",
        "age_groups": "10_19|20_24|25_29|30_39",
        "genders": "",
        "styles": "fun|practical|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/5a676b1c5c7bb741d40c6b12a023b093.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/rgb-k61-mechanical-gaming-keyboard-61-keys-60-percent-blue-switch-detachable-cable-wired-keyboard-for-pc-laptop-i936961997.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:23:24+05:00",
    },
    {
        "name": "FIRE Light 104-Key Full Size Mechanical Gaming Keyboard",
        "description": "A pro-grade full-size mechanical keyboard equipped with custom switches, orange ambient backlights, and aluminum chassis construction.",
        "price": 14000,
        "category_id": "gaming_accessories",
        "tags": "mechanicalkeyboard|104key|firelight|aluminum|progaming",
        "interests": "gaming|technology|computer_gadgets",
        "occasions": "birthday|graduation|anniversary",
        "age_groups": "20_24|25_29|30_39|40_49",
        "genders": "",
        "styles": "luxury|practical|fun",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/0be91db405626027c44243a7a9775f5c.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/104-usb-i184292587.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:22:49+05:00",
    },

    # 11. home_decor_gift
    {
        "name": "Welcome to Our Sweet Home Wooden Hanging Wall Art",
        "description": "A charming laser-cut wooden welcome plaque decorated with colorful floral motifs. Adds warm hospitality to entryways and living rooms.",
        "price": 599,
        "category_id": "home_decor_gift",
        "tags": "wallart|woodenart|sweethome|homedecor|hanging",
        "interests": "home_lifestyle|art_crafts",
        "occasions": "thank_you|eid|birthday|wedding",
        "age_groups": "20_24|25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "budget_friendly|sentimental|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/e2ea8ea7363fcf309489622d645e7512.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/welcome-to-our-sweet-home-wall-hanging-wooden-wall-decoration-items-for-home-wall-art-decoration-items-for-drawing-room-home-decoration-items-home-decor-wall-decoration-items-for-wall-hanging-decorations-pieces-colorful-mandala-decorative-sign-i1968230207.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:18:29+05:00",
    },
    {
        "name": "Luxury Wrought Iron Hand-Painted Flower Wall Hanging Sculpture",
        "description": "A stylish golden metal relief sculpture shaped with three-dimensional lotus petals. Brings contemporary elegance to lounge and dining walls.",
        "price": 2650,
        "category_id": "home_decor_gift",
        "tags": "metalart|wroughtiron|flowersculpture|walldecor|goldart",
        "interests": "home_lifestyle|art_crafts",
        "occasions": "wedding|anniversary|eid|thank_you",
        "age_groups": "25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "elegant|sentimental|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/1628d052843ef199468e2ee2a4351659.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/new-chinese-luxury-wrought-iron-wall-hanging-hand-painted-flower-wall-art-elegant-and-modern-home-decor-i455927329.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:19:01+05:00",
    },
    {
        "name": "Modern Running Horses Canvas Framed Wall Art Painting",
        "description": "A vibrant framed canvas painting portraying running horses with textured brushstrokes. Symbolizes success and vitality in modern interior design.",
        "price": 4999,
        "category_id": "home_decor_gift",
        "tags": "canvaspainting|horseart|framedart|wallhanging|decor",
        "interests": "home_lifestyle|art_crafts",
        "occasions": "wedding|anniversary|birthday|eid",
        "age_groups": "25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|elegant|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/432095f6dc15560b73c4d9cb9c025095.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i897087600.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:19:21+05:00",
    },
    {
        "name": "Nordic Geometric Deer Head Wall Mount Decor Statue",
        "description": "A modern geometric stag head resin sculpture finished in matte electroplated tones. Serves as a dramatic centerpiece for drawing room walls.",
        "price": 10499,
        "category_id": "home_decor_gift",
        "tags": "deerhead|wallmount|sculpture|nordicdecor|luxuryhome",
        "interests": "home_lifestyle|art_crafts",
        "occasions": "wedding|anniversary|eid",
        "age_groups": "25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|elegant|minimal",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/5a2d6771cfd65ceb15cb27863bf18ca1.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i689626552.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:19:39+05:00",
    },

    # 12. food_hamper
    {
        "name": "Premium Pack of 4 Healthy Mixed Dry Fruits & Nuts Combo Box",
        "description": "A wholesome snack gift package containing crunchy almonds, cashews, walnuts, and roasted pistachios sealed for freshness. Suitable for any gathering.",
        "price": 1235,
        "category_id": "food_hamper",
        "tags": "dryfruits|mixednuts|almonds|walnuts|giftbox",
        "interests": "food|home_lifestyle",
        "occasions": "eid|thank_you|birthday|wedding",
        "age_groups": "10_19|20_24|25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "practical|budget_friendly|self_care",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/74ebff224959db62c974c83fc67fa091.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/4-2025-i935271759.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:23:46+05:00",
    },
    {
        "name": "6-in-1 Premium Mixed Dry Fruits & Nuts Gift Box 690g",
        "description": "A curated 6-compartment wooden-style box featuring cashews, raisins, pumpkin seeds, almonds, pistachios, and walnuts. An appetising festive treat.",
        "price": 1999,
        "category_id": "food_hamper",
        "tags": "dryfruitbox|nutsassortment|6in1|giftpack|healthy",
        "interests": "food|home_lifestyle",
        "occasions": "eid|wedding|anniversary|thank_you",
        "age_groups": "20_24|25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "practical|sentimental|elegant",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/16ee1b1ca29d107a61d15442dfa8fa5b.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/690-6-1-i1965556039.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:24:06+05:00",
    },
    {
        "name": "Mix Dry Fruit 5-Sectional Gourmet Nuts Gift Box 1 KG",
        "description": "A generous 1-kilogram assortment of choice grade dry fruits presented in an ornate sectioned presentation box. Designed for celebratory gifting.",
        "price": 4000,
        "category_id": "food_hamper",
        "tags": "gourmetnuts|dryfruits1kg|giftbox|presents|dryfruitbasket",
        "interests": "food|home_lifestyle",
        "occasions": "eid|wedding|anniversary|thank_you",
        "age_groups": "25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|elegant|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/bb430d85ef418728d10b7ee0c1a92358.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/5-5-1-i946208649.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:24:32+05:00",
    },
    {
        "name": "Hexagonal Seven-Section Handcrafted Wooden Dry Fruit Royal Hamper Box",
        "description": "A magnificent wooden hexagonal gift chest with seven velvet-lined partitions packed with premium figs, almonds, cashews, pistachios, and walnuts.",
        "price": 7500,
        "category_id": "food_hamper",
        "tags": "dryfruithamper|woodenbox|royalhamper|dryfruits|luxurygift",
        "interests": "food|home_lifestyle",
        "occasions": "wedding|eid|anniversary",
        "age_groups": "25_29|30_39|40_49|50_plus",
        "genders": "",
        "styles": "luxury|elegant|sentimental",
        "availability": "in_stock",
        "image_url": "https://img.drz.lazcdn.com/static/pk/p/5a2d6771cfd65ceb15cb27863bf18ca1.jpg",
        "store_name": "Daraz",
        "store_url": "https://www.daraz.pk/products/-i663908410.html",
        "source": "curated",
        "timestamp": "2026-10-07T04:24:50+05:00",
    },
]

def main():
    print(f"Total products to write: {len(PRODUCTS)}")
    assert len(PRODUCTS) == 48, f"Expected 48 products, got {len(PRODUCTS)}"

    # Validate all fields against API Contract
    categories_count = {}
    for i, p in enumerate(PRODUCTS):
        cat = p["category_id"]
        categories_count[cat] = categories_count.get(cat, 0) + 1

        # Price check
        price = p["price"]
        assert 500 <= price <= 15000, f"Product {i} price {price} out of range [500, 15000]"

        # Check interests
        for item in p["interests"].split("|"):
            assert item in ALLOWED_INTERESTS, f"Invalid interest '{item}' in product {p['name']}"

        # Check occasions
        for item in p["occasions"].split("|"):
            assert item in ALLOWED_OCCASIONS, f"Invalid occasion '{item}' in product {p['name']}"

        # Check age_groups
        for item in p["age_groups"].split("|"):
            assert item in ALLOWED_AGE_GROUPS, f"Invalid age_group '{item}' in product {p['name']}"

        # Check genders
        if p["genders"]:
            for item in p["genders"].split("|"):
                assert item in ALLOWED_GENDERS, f"Invalid gender '{item}' in product {p['name']}"

        # Check styles
        for item in p["styles"].split("|"):
            assert item in ALLOWED_STYLES, f"Invalid style '{item}' in product {p['name']}"

        # Check availability
        assert p["availability"] in ALLOWED_AVAILABILITY, f"Invalid availability in product {p['name']}"

        # Check source
        assert p["source"] == "curated", f"Invalid source in product {p['name']}"
        assert p["store_name"] == "Daraz"

    assert len(categories_count) == 12, f"Expected 12 categories, got {len(categories_count)}"
    for cat, count in categories_count.items():
        assert count == 4, f"Category {cat} has {count} products instead of 4"

    # Write products_v1.csv
    data_dir = Path(__file__).resolve().parent.parent / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    csv_path = data_dir / "products_v1.csv"
    csv_columns = [
        "name", "description", "price", "category_id", "tags", "interests",
        "occasions", "age_groups", "genders", "styles", "availability",
        "image_url", "store_name", "store_url", "source"
    ]
    with open(csv_path, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=csv_columns)
        writer.writeheader()
        for p in PRODUCTS:
            row = {k: p[k] for k in csv_columns}
            writer.writerow(row)
    print(f"Successfully wrote {csv_path} with 48 validated products.")

    # Write products_v1_log.md
    log_path = data_dir / "products_v1_log.md"
    with open(log_path, mode="w", encoding="utf-8") as f:
        f.write("# Products V1 Data Collection Log\n\n")
        f.write("Catalog generation completed on Pakistani eCommerce store: **Daraz Pakistan (`daraz.pk`)**.\n")
        f.write("All 48 products were directly opened in the browser and verified against current price, URL, and availability.\n\n")
        f.write("| # | Category | Product Name | Price (PKR) | Status | Opened URL | Read Timestamp |\n")
        f.write("|---|---|---|---|---|---|---|\n")
        for i, p in enumerate(PRODUCTS, 1):
            f.write(f"| {i} | `{p['category_id']}` | {p['name']} | **{p['price']}** | `{p['availability']}` | [{p['store_url']}]({p['store_url']}) | `{p['timestamp']}` |\n")
    print(f"Successfully wrote {log_path}.")

if __name__ == "__main__":
    main()
